apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  selector:
    app: demo
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.drewspace.ro`)
      kind: Rule
      services:                      
      - kind: Service
        name: demo-service
        namespace: demo
        port: http
        passHostHeader: true
  tls:
    certResolver: letsencrypt
